### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Craigtut** [bolav/fusepm#2]
Hey, I was trying to install your CameraPanel package but fusepm throws an error no matter how it is run:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'hosted-git-info'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/fusepm/lib/install.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Maybe I'm just doing something wrong?

**Comment by Craigtut** [comment]
I either just didn't have dependancies installed (hosted-git-info, clarinet, sax) or they needed to be included - dunno if this is an issue still

**Comment by bolav** [comment]
Sorry. This commit should fix it: https://github.com/bolav/fusepm/commit/4604b9c9db480efcbce1583abf252c35ea3f6a31

**Comment by LuisRodriguezLD** [comment]
Not sure if this should be reopened. I just had a similar issue 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './xregexp' from '/Users/luis/node_modules/xregexp'
    at /usr/local/lib/node_modules/fusepm/node_modules/resolve/lib/async.js:59:35
    at load (/usr/local/lib/node_modules/fusepm/node_modules/resolve/lib/async.js:77:43)
    at onex (/usr/local/lib/node_modules/fusepm/node_modules/resolve/lib/async.js:100:31)
    at /usr/local/lib/node_modules/fusepm/node_modules/resolve/lib/async.js:23:47
    at /usr/local/lib/node_modules/fusepm/node_modules/npm/node_modules/graceful-fs/polyfills.js:264:29
    at FSReqWrap.oncomplete (fs.js:123:15)
 ```
